# linear algebra
Following the guide from MXNet UC Bekeley Course on the Apache MXNet youtube channel

In [3]:
from mxnet import nd
import mxnet as mx
print ('mx version ', mx.__version__)

mx version  1.9.0


In MXNet scalars are NDArrays with one element

In [3]:
x = nd.array([3.0])
y = nd.array([2.0])

print('x + y = ', x + y)
print('x - y = ', x - y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', x ** y)
print('x ** y = ', nd.power(x,y))

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x - y =  
[1.]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


We can convert any NDArray to a python float by calling its asscalar method.  NOTE: this is a bad idea.  The NDArray has to stop doing anything else in order to hand the result and process control back to Python.  Its not done in parallel.

In [4]:
print(x)
print(x.asscalar())


[3.]
<NDArray 1 @cpu(0)>
3.0


# Vectors
Vectors are [1, 3, 4, 2]  as a 1D NDArray

In [5]:
x = nd.arange(5)
print('x = ', x)

x =  
[0. 1. 2. 3. 4.]
<NDArray 5 @cpu(0)>


In [6]:
x[3]


[3.]
<NDArray 1 @cpu(0)>

# Length, dimensionality and shape
The length of a vector is commonly called its *dimension*.  As an ordianry Python array, we can acces the length of an NDArray by calling Python's built-in len() function.

We can also access a vectors length via its `.shape` attribute.  The shape is a tuple that lists it dimensionality along each of its axes.


In [7]:
x.shape

(5,)

The word dimension is overloaded between number of axes and number of elements.  To avoid confusion, when we say 2D array or 3D array, we mean an array with 2 or 3 axes respectively.  But, if we say `n-dimensional` vector, we mean a vector of length `n`.

In [8]:
a = 2
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print('a * x = ', a * x)
print('a * x + y = ', a * x + y)

a * x =  
[2. 4. 6.]
<NDArray 3 @cpu(0)>
a * x + y =  
[12. 24. 36.]
<NDArray 3 @cpu(0)>


# Matrices

Just as vectors generalize scalars from order 0 to order 1, matrices generalize vectors from 1D to 2D.  Matrices, which we'll typically denote with capital letters (A,B,C), are represented in codes as arrays with 2 axes.  Visually, we can draw a matrix as a table, where each entry $a_{ij}$ belongs to the i-th row and j-th column.

\begin{pmatrix}
a_{11} & a_{12} & a_{1m}\\
a_{21} & a_{22} & a_{2m}\\
a_{..} & a_{..} & a_{..}\\
a_{n1} & a_{n2} & a_{nm}
\end{pmatrix}

In [9]:
print(nd.arange(20))
A = nd.arange(20).reshape((2,10)) # NOTE, rows, columns
print('A = ', A)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
<NDArray 20 @cpu(0)>
A =  
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
<NDArray 2x10 @cpu(0)>


We can access elements $a_{ij}$ by specifying row *i* and column *j*.  Leaving them blank, selects all?

Selecting via `:` also takes all elements in the respective dimension.

We can transpose the matrix with the `T` method.  That is, if $B=A^{T}$ then $b_{ij}=a_{ji}\,\, \forall{i,j}$

In [10]:
print('A[1] = ', A[1])

A[1] =  
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
<NDArray 10 @cpu(0)>


In [11]:
print('A[1,:] = ', A[1,:])

A[1,:] =  
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
<NDArray 10 @cpu(0)>


In [12]:
print('A.T = ', A.T)

A.T =  
[[ 0. 10.]
 [ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]
 [ 7. 17.]
 [ 8. 18.]
 [ 9. 19.]]
<NDArray 10x2 @cpu(0)>


## Subset a matrix

slice url 

https://mxnet.apache.org/versions/master/api/python/docs/api/legacy/ndarray/ndarray.html?highlight=mxnet%20ndarray%20arange#mxnet.ndarray.slice

In [13]:
four_by_four = nd.arange(16).reshape(4,4)
print('four_by_four = ', four_by_four)

four_by_four =  
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
<NDArray 4x4 @cpu(0)>


In [14]:
# when you use the :, its all rows.  But if numbers are on either side its a range, where the end is exclusive.
two_by_two = four_by_four[0:2,1:3]
print('two_by_two = ', two_by_two)

two_by_two =  
[[1. 2.]
 [5. 6.]]
<NDArray 2x2 @cpu(0)>


In [16]:
# you can create a sliced copied
another2x2 = four_by_four.slice(begin=(1,1), end=(3,3))
print('another2x2 = ', another2x2)

another2x2 =  
[[ 5.  6.]
 [ 9. 10.]]
<NDArray 2x2 @cpu(0)>


# Tensors
Just as vectors genralize scalars, and matrices generalize vectors, we can increase the number of axes.  When working with images the axes correspond to the height, width and the three RGB color channels.

In [12]:
X = nd.arange(24).reshape((2,3,4))  # two submaxtrices of three rows by four columns
print('X = ', X)
print('X.shape = ', X.shape)


X =  
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>
X.shape =  (2, 3, 4)


# Basic properties of tensor artihmetic

Given two tensors `X` and `Y` with the same shape, $\alpha X + Y$ has the same shape (numerical mathematicians call this the `AXPY` operation)

In [13]:
a = 2
x = nd.ones(3)
y = nd.zeros(3)
print('x.shape = ', x.shape)
print('y.shape = ', y.shape)
print('(a * x).shape = ', (a * x).shape)
print('(a * x + y).shape = ', (a * x + y).shape)

x.shape =  (3,)
y.shape =  (3,)
(a * x).shape =  (3,)
(a * x + y).shape =  (3,)


# sums and means
In math we express sums using the $\sum$ symbol.  To express the sum of elements in a vector `u` of length `d`, we can write $\sum_{i=i}^{i=d}{u_{i}}$   In code, we can just call `nd.sum()`

In [14]:
x = nd.arange(12)
x = x.reshape((3,4))
print('x = ', x)
print('nd.sum(x) = ', nd.sum(x))

x =  
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>
nd.sum(x) =  
[66.]
<NDArray 1 @cpu(0)>


Sum along a row

In [15]:
print('nd.sum(x,0) = ', nd.sum(x,0))
# or
print('nd.sum(x,0) = ', nd.sum(x,axis=0))


nd.sum(x,0) =  
[12. 15. 18. 21.]
<NDArray 4 @cpu(0)>
nd.sum(x,0) =  
[12. 15. 18. 21.]
<NDArray 4 @cpu(0)>


sum along a column

In [16]:
print('nd.sum(x,0) = ', nd.sum(x,axis=1))
# or
print('nd.sum(x,0) = ', nd.sum(x,1))


nd.sum(x,0) =  
[ 6. 22. 38.]
<NDArray 3 @cpu(0)>
nd.sum(x,0) =  
[ 6. 22. 38.]
<NDArray 3 @cpu(0)>


sum along a row and column

In [17]:
print('nd.sum(x,0) = ', nd.sum(x,(0,1)))


nd.sum(x,0) =  
[66.]
<NDArray 1 @cpu(0)>


# Mean
A related quantity is the mean.  We calculate the mean by dividing the sum by the total number of elements.  In code this is `nd.mean()`

$$mean(u) = \frac{1}{d} \sum_{i=1}^{i=d} u_{i} $$

and

$$mean(A) = \frac{1}{n*m} \sum_{i=1}^{i=m} \sum_{j=1}^{j=n} a_{ij} $$

In [18]:
print('A = ', A)
print('nd.mean(A) = ', nd.mean(A))
print('nd.sum(A) / A.size = ', nd.sum(A) / A.size)

A =  
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
<NDArray 2x10 @cpu(0)>
nd.mean(A) =  
[9.5]
<NDArray 1 @cpu(0)>
nd.sum(A) / A.size =  
[9.5]
<NDArray 1 @cpu(0)>


# Dot products

Given two vectors `u` and `v`, the dot product $u^Tv$ is a sum over the products of the corresponding elements: $$u^Tv = \sum_{i=1}^{i=d} u_i * v_i$$

In [19]:
x = nd.arange(4) + 1.0
y = nd.ones(4)
print('x = ', x)
print('y = ', y)
print('nd.dot(x,y) = ', nd.dot(x,y))
# also equivalent
print('(x * y).sum() = ', (x * y).sum())

x =  
[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>
y =  
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)>
nd.dot(x,y) =  
[10.]
<NDArray 1 @cpu(0)>
(x * y).sum() =  
[10.]
<NDArray 1 @cpu(0)>


Note that we can express the dot product of two vectors `nd.dot(u,v)` equivalently by performing an element-wise multiplicatoins and then a sum:

In [20]:
nd.sum(x * y)


[10.]
<NDArray 1 @cpu(0)>

# Matrix-vector products

\begin{align}
\begin{vmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{vmatrix}
\begin{vmatrix} x \\ y \end{vmatrix} = 
\begin{vmatrix}
a_1^T x \\
a_2^T y
\end{vmatrix} = 
\begin{vmatrix}
x a_{11} + y a_{12} \\
x a_{12} + y a_{22}
\end{vmatrix}
\end{align}

$\in$ is member of

$\newcommand{\R}{\mathbb{R}} \R$ is real number. all numbers negative and positive including fractions


So you can think of multiplication by a matrix $\newcommand{\R}{\mathbb{R}} A\in\R^{mxn}$ as trans that projects vectors from $\R^m to \R^n$ 

We can also use matrix-vector products to describe the calculations of each layer in a neural network.  Expressing matrix-vector products in code with `ndarray`, we use the same `nd.dot()` function as for dot products.

In [21]:
print('A = ', A) # a 2x10
print('x = ', x) # a 1x4

# He did this.  It does not work for me.  I look in the online help text
# and nothing is mentioned about truncating rows. ie. if 4 columns it needs 5 rows
# and not three as in his text.  (Another reason to look for the git repo rather than typing along!)
#A = A.reshape((3,4))   

# later he refers to this as 3x4.  He must have had a 2x6?

# My choice
A = A.reshape((5,4))
print('A now is = ', A)


# * is an element by element multiply. it mults X by each row.
# first row is 1*0  2*1 3*2 4*3
# second row is 1*4 2*5 3*6 4*7 etc
print('A*x = ', A*x)

# dot is a row sum. Notice its a sum across a row
print('nd.dot(A,x) = ', nd.dot(A,x))


# 
# He mentioned matlab .* notation is equivalent to nd *

# He also mentions broadcast of repeat entries of X until you get all elements of A.


A =  
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
<NDArray 2x10 @cpu(0)>
x =  
[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>
A now is =  
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
<NDArray 5x4 @cpu(0)>
A*x =  
[[ 0.  2.  6. 12.]
 [ 4. 10. 18. 28.]
 [ 8. 18. 30. 44.]
 [12. 26. 42. 60.]
 [16. 34. 54. 76.]]
<NDArray 5x4 @cpu(0)>
nd.dot(A,x) =  
[ 20.  60. 100. 140. 180.]
<NDArray 5 @cpu(0)>


# Matrix-Matrix multiplication

If you have gotten the hang of dot products and matrix-vector multiplication, then matrix-matrix multiplications should be pretty straight forward.

Say we have two matrices, $\newcommand{\R}{\mathbb{R}} A\in\R^{nxk}\, and\, B\in\R^{kxm}$

\begin{align}
A=\begin{vmatrix}
a_{11} & a_{12} \\
a_{21} & a_{nk}
\end{vmatrix}
B=\begin{vmatrix}
b_{11} & b_{12} \\
b_{21} & b_{km}
\end{vmatrix}
\end{align}


You can think of the matrix-matrix multiplication $AB$ as simply performing `m` matrix-vector products and stiching the results together. 

\begin{align}
AB=\begin{vmatrix}
\cdots & a_1^T & \cdots \\
\cdots & a_2^T & \cdots \\
\cdots & a_n^T & \cdots 
\end{vmatrix}
\begin{vmatrix}
\cdots & \cdots & \cdots \\
b_{1} & b_{2} & b_{m} \\
\cdots & \cdots & \cdots 
\end{vmatrix}
=\begin{vmatrix}
a_1^Tb_1 & a_1^Tb_2 & .. & a_1^Tb_m \\
a_2^Tb_1 & a_2^Tb_2 & .. & a_1^Tb_m \\
a_n^Tb_1 & a_n^Tb_2 & .. & a_n^Tb_m
\end{vmatrix}
\end{align}

In [22]:
A=nd.arange(4).reshape((2,2))
print('A = ', A)
B=nd.arange(1, stop=5, step=1).reshape((2,2))
print('B = ', B)

nd.dot(A,B)

A =  
[[0. 1.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>
B =  
[[1. 2.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>



[[ 3.  4.]
 [11. 16.]]
<NDArray 2x2 @cpu(0)>

# Norms

All norms must satisfy a handful of properties:

* $  \left\Vert  \alpha A \right\Vert = \begin{vmatrix} \alpha \end{vmatrix} \left\Vert A \right\Vert$
* $  \left\Vert A + B \right\Vert \leq \left\Vert A \right\Vert + \left\Vert B \right\Vert$
* $  \left\Vert A  \right\Vert \geq 0$
* $  \text{If }\forall\,i,j,a_{ij} = 0, then \left\Vert A  \right\Vert = 0$

To calculate the $L_{2}$ norm, we can just call `nd.norm()`

In [23]:
nd.norm(x)


[5.477226]
<NDArray 1 @cpu(0)>

To calculate the $L_1$ norm we can simply perform the absolute value and then sum over elements.

https://mxnet.apache.org/versions/1.6/api/r/docs/api/mx.symbol.sum.html

In [29]:
print("L1 norm = ", nd.sum(nd.sum(x)))
# or
print("L1 norm = ", x.abs().sum())


L1 norm =  
[10.]
<NDArray 1 @cpu(0)>
L1 norm =  
[10.]
<NDArray 1 @cpu(0)>
