In [1]:
import gluoncv as gcv
import mxnet as mx
# mxnet NDarray 
from mxnet import nd

# MXNet Gluon Neural network layers.
from mxnet.gluon import nn

# optional for displaying the image
import matplotlib.pyplot as plt
import numpy as np
import os
import math


In [4]:
def build_rot_matrix(angle):
    #  a  b
    #  c  d
    
    # calculate terms
    a = math.cos(x)
    b = -math.sin(x)
    c = math.sin(x)
    d = math.cos(x)

    # print("a = ", a)
    # print("b = ", b)
    # print("c = ", c)
    # print("d = ", d)
    
    # build np array
    np_array = np.array([
        [a,b],
        [c,d]
    ])
    
    # build mx.nd array
    nd_array = mx.nd.array(np_array)
    
    return nd_array

In [5]:
x=0.5*math.pi

rotate_90 = build_rot_matrix(x)
print('rotate by 90 nd array is ', rotate_90)

rotate by 90 nd array is  
[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]
<NDArray 2x2 @cpu(0)>


In [10]:
# batch 1
in_data = nd.arange(9).reshape((1,3,3))
print('in_data is ', in_data)
orig_image = in_data[0]
print('orig_image ', orig_image)

in_data is  
[[[0. 1. 2.]
  [3. 4. 5.]
  [6. 7. 8.]]]
<NDArray 1x3x3 @cpu(0)>
orig_image  
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
<NDArray 3x3 @cpu(0)>


In [11]:
# setup an ouptut array with all nines, so I can see overwrites with new values
out_data = nd.ones(9).reshape((3,3))*9
# out_data also needs to be in batch form
out_data = nd.expand_dims(out_data, axis=0)
print('out_data is ', out_data)
rotated_image=out_data[0]
print('rotated_image', rotated_image)

out_data is  
[[[9. 9. 9.]
  [9. 9. 9.]
  [9. 9. 9.]]]
<NDArray 1x3x3 @cpu(0)>
rotated_image 
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
<NDArray 3x3 @cpu(0)>


In [12]:
# setup a rotation matrix
rotate_data = rotate_90
print('rotate_90 ', rotate_data)

rotate_90  
[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]
<NDArray 2x2 @cpu(0)>


In [14]:
# NDArrayIter(data, label=None, batch_size=1, shuffle=False, 
#            last_batch_handle='pad', data_name='data', 
#            label_name='softmax_label')
#
# Ignore the label parameter.
dataiter = mx.io.NDArrayIter(in_data, batch_size=1, shuffle=False, last_batch_handle='discard')
#batch_index = [0]
for batch in dataiter:
    
    print('loop entry - a single batch - a single image in batch.data[0] from what is in in_data')
    #print ('batch.data[0] = ', batch.data[0].asnumpy())
    #print ('batch.data[0].shape = ', batch.data[0].shape)
    # Does this copy or get an alias to the input image?
    input_img = batch.data[0]
    #print ('input_img = ', input_img.asnumpy())
    print ('input_img.shape = ', input_img.shape)
    
    # this will print the axis including the batch axis
    # print('indicies are ', mx.nd.contrib.index_array(entire_img) )
    # this will print the x,y axis and ignore the batch
    input_img_indexes = mx.nd.contrib.index_array(input_img, axes=(1, 2))
    print('indexes are: ', input_img_indexes)
    print ('input_img_indexes.shape = ', input_img_indexes.shape)
    
    
    
    # Try to assign input data to output data based upon indicies
    orig_indexes = mx.nd.reshape(input_img_indexes, shape=(9,2))
    print('orig_indexes ', orig_indexes)
    orig_indexes = orig_indexes.astype("float32")
    
    # I've seen one variant where matrix-matrix multiply 
    # is done with .T.  why?
    new_indexes = nd.dot(orig_indexes, rotate_data) 
    print('new_indexes = ', new_indexes)
    new_indexes = new_indexes.astype('int64')
    print('new_indexes = ', new_indexes)
    new_indexes = new_indexes + nd.array(nd.array([0, 2])).astype('int64')
    print('new_indexes after shift to positive', new_indexes)

    print('rotated_image ', rotated_image)
    print('rotated_image.shape ', rotated_image.shape)
    rotated_image = orig_image[new_indexes[:,0],new_indexes[:,1]]
    print('rotated_image ', rotated_image)
    rotated_image = rotated_image.reshape(3,3)
    print('rotated_image ', rotated_image)


loop entry - a single batch - a single image in batch.data[0] from what is in in_data
input_img.shape =  (1, 3, 3)
indexes are:  
[[[[0 0]
   [0 1]
   [0 2]]

  [[1 0]
   [1 1]
   [1 2]]

  [[2 0]
   [2 1]
   [2 2]]]]
<NDArray 1x3x3x2 @cpu(0)>
input_img_indexes.shape =  (1, 3, 3, 2)
orig_indexes  
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
<NDArray 9x2 @cpu(0)>
new_indexes =  
[[ 0.0000000e+00  0.0000000e+00]
 [ 1.0000000e+00  6.1232343e-17]
 [ 2.0000000e+00  1.2246469e-16]
 [ 6.1232343e-17 -1.0000000e+00]
 [ 1.0000000e+00 -1.0000000e+00]
 [ 2.0000000e+00 -1.0000000e+00]
 [ 1.2246469e-16 -2.0000000e+00]
 [ 1.0000000e+00 -2.0000000e+00]
 [ 2.0000000e+00 -2.0000000e+00]]
<NDArray 9x2 @cpu(0)>
new_indexes =  
[[ 0  0]
 [ 1  0]
 [ 2  0]
 [ 0 -1]
 [ 1 -1]
 [ 2 -1]
 [ 0 -2]
 [ 1 -2]
 [ 2 -2]]
<NDArray 9x2 @cpu(0)>
new_indexes after shift to positive 
[[0 2]
 [1 2]
 [2 2]
 [0 1]
 [1 1]
 [2 1]
 [0 0]
 [1 0]
 [2 0]]
<NDArray 9x2 @cpu(0)>
rotated_image  
[2. 5. 8. 1. 4. 7. 0